package com.nicktz.revoluttest.utils

import com.nicktz.revoluttest.R

object CurrencyFlags {
    val byCurrency: Map<String, Int> =
        mapOf(
            "AED" to R.drawable.ic_flag_aed,
            "ARS" to R.drawable.ic_flag_ars,
            "AUD" to R.drawable.ic_flag_aud,
            "BDT" to R.drawable.ic_flag_bdt,
            "BGN" to R.drawable.ic_flag_bgn,
            "BRL" to R.drawable.ic_flag_brl,
            "CAD" to R.drawable.ic_flag_cad,
            "CHF" to R.drawable.ic_flag_chf,
            "CLP" to R.drawable.ic_flag_clp,
            "CNY" to R.drawable.ic_flag_cny,
            "CRC" to R.drawable.ic_flag_crc,
            "CZK" to R.drawable.ic_flag_czk,
            "DKK" to R.drawable.ic_flag_dkk,
            "EGP" to R.drawable.ic_flag_egp,
            "EUR" to R.drawable.ic_flag_eur,
            "GBP" to R.drawable.ic_flag_gbp,
            "GEL" to R.drawable.ic_flag_gel,
            "GHS" to R.drawable.ic_flag_ghs,
            "HKD" to R.drawable.ic_flag_hkd,
            "HRK" to R.drawable.ic_flag_hrk,
            "HUF" to R.drawable.ic_flag_huf,
            "IDR" to R.drawable.ic_flag_idr,
            "ILS" to R.drawable.ic_flag_ils,
            "INR" to R.drawable.ic_flag_inr,
            "ISK" to R.drawable.ic_flag_isk,
            "JPY" to R.drawable.ic_flag_jpy,
            "KES" to R.drawable.ic_flag_kes,
            "KRW" to R.drawable.ic_flag_krw,
            "LKR" to R.drawable.ic_flag_lkr,
            "MAD" to R.drawable.ic_flag_mad,
            "MXN" to R.drawable.ic_flag_mxn,
            "MYR" to R.drawable.ic_flag_myr,
            "NGN" to R.drawable.ic_flag_ngn,
            "NOK" to R.drawable.ic_flag_nok,
            "NPR" to R.drawable.ic_flag_npr,
            "NZD" to R.drawable.ic_flag_nzd,
            "PEN" to R.drawable.ic_flag_pen,
            "PHP" to R.drawable.ic_flag_php,
            "PKR" to R.drawable.ic_flag_pkr,
            "PLN" to R.drawable.ic_flag_pln,
            "RON" to R.drawable.ic_flag_ron,
            "RUB" to R.drawable.ic_flag_rub,
            "SEK" to R.drawable.ic_flag_sek,
            "SGD" to R.drawable.ic_flag_sgd,
            "THB" to R.drawable.ic_flag_thb,
            "TRY" to R.drawable.ic_flag_try_,
            "TZS" to R.drawable.ic_flag_tzs,
            "UAH" to R.drawable.ic_flag_uah,
            "UGX" to R.drawable.ic_flag_ugx,
            "USD" to R.drawable.ic_flag_usd,
            "VND" to R.drawable.ic_flag_vnd,
            "XOF" to R.drawable.ic_flag_xof,
            "ZAR" to R.drawable.ic_flag_zar
        )
}
